package com.wakaztahir.codeeditor.model

import com.wakaztahir.codeeditor.prettify.lang.*

enum class CodeLang(val value: List<String>) {
    Default(listOf("default-code", "default-markup")),
    HTML(listOf("default-markup")),
    C(listOf("c")),
    CPP(listOf("cpp")),
    ObjectiveC(listOf("cxx")),
    CSharp(listOf("cs")),
    Java(listOf("java")),
    Bash(listOf("bash")),
    Python(listOf("python")),
    Perl(listOf("perl")),
    Ruby(listOf("ruby")),
    JavaScript(listOf("javascript")),
    CoffeeScript(listOf("coffee")),
    Rust(listOf("rust")),
    Appollo(listOf("apollo")),
    Basic(listOf("basic")),
    Clojure(listOf("clj")),
    CSS(listOf("css")),
    Dart(listOf("dart")),
    Erlang(listOf("erlang")),
    Go(listOf("go")),
    Haskell(listOf("hs")),
    Lisp(listOf("lisp")),
    Llvm(listOf("llvm")),
    Lua(listOf("lua")),
    Matlab(listOf("matlab")),
    ML(listOf("ml")),
    OCAML(listOf("ml")),
    SML(listOf("ml")),
    FSharp(listOf("fs")),
    Mumps(listOf("mumps")),
    N(listOf("n", "nemerle")),
    Pascal(listOf("pascal")),
    R(listOf("r", "s", "R", "S", "Splus")),
    Rd(listOf("Rd", "rd")),
    Scala(listOf("scala")),
    SQL(listOf("sql")),
    Tex(listOf("latex", "tex")),
    VB(listOf("vb", "vbs")),
    VHDL(listOf("vhdl", "vhd")),
    Tcl(listOf("tcl")),
    Wiki(listOf("wiki.meta")),
    XQuery(listOf("xq", "xquery")),
    YAML(listOf("yaml", "yml")),
    Markdown(listOf("md", "markdown")),
    JSON(listOf("json")),
    XML(listOf("xml")),
    Proto(listOf("proto")),
    RegEx(listOf("regex")),
    Ex(LangEx.fileExtensions),
    Kotlin(LangKotlin.fileExtensions),
    Lasso(LangLasso.fileExtensions),
    Logtalk(LangLogtalk.fileExtensions),
    Swift(LangSwift.fileExtensions),
}